language: elixir
elixir: 1.9
branches:
  only:
    - master
env:
  - MIX_ENV=test
script:
  - mix format --check-formatted
  - mix do compile --warnings-as-errors
  - mix credo --strict
  - mix coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
